-- Offline tests for pure game logic. Run scripts\test.ps1 (LuaJIT = Lua 5.1, like WoW).
local ns = {}
local function load(file) assert(loadfile(file))("Bonfire", ns) end
load("Roll.lua")
load("Money.lua")
load("Ledger.lua")
load("Bets.lua")
load("Games/Embers.lua")
load("Games/Deathroll.lua")
load("Games/OddManOut.lua")

local passed, failed = 0, 0
local function test(name, fn)
	local ok, err = pcall(fn)
	if ok then passed = passed + 1 else failed = failed + 1; print("FAIL " .. name .. ": " .. tostring(err)) end
end
local function eq(actual, expected)
	if actual ~= expected then error(("expected %s, got %s"):format(tostring(expected), tostring(actual)), 2) end
end

-- Roll parsing ---------------------------------------------------------------
local enUS = ns.RollPattern("%s rolls %d (%d-%d)")

test("parses an enUS roll", function()
	local who, roll, low, high = ns.ParseRoll("Oppa rolls 42 (1-100)", enUS)
	eq(who, "Oppa"); eq(roll, 42); eq(low, 1); eq(high, 100)
end)

test("keeps realm suffixes", function()
	eq(ns.ParseRoll("Oppa-ClassicBetaPvE rolls 6 (1-6)", enUS), "Oppa-ClassicBetaPvE")
end)

test("ignores other system text", function()
	eq(ns.ParseRoll("Oppa has come online.", enUS), nil)
	eq(ns.ParseRoll("Oppa rolls 42 (1-100) extra", enUS), nil)
end)

test("handles positional locale formats", function()
	local who, roll = ns.ParseRoll("Oppa wirft 5 (1-6)", ns.RollPattern("%1$s wirft %2$d (%3$d-%4$d)"))
	eq(who, "Oppa"); eq(roll, 5)
end)

-- Embers ---------------------------------------------------------------------
local Embers = ns.Games.embers

test("rolls add to every stoking pot", function()
	local s = Embers.New({ "A", "B" }, 3)
	Embers.Roll(s, 4); Embers.Roll(s, 5)
	eq(s.players.A.pot, 9); eq(s.players.B.pot, 9)
end)

test("banking keeps the pot and sits you out", function()
	local s = Embers.New({ "A", "B" }, 3)
	Embers.Roll(s, 4)
	eq(Embers.Bank(s, "A"), true)
	Embers.Roll(s, 6)
	eq(s.players.A.total, 4); eq(s.players.A.pot, 0); eq(s.players.B.pot, 10)
	eq(Embers.Bank(s, "A"), false)
end)

test("a 1 wipes unbanked pots and starts the next round", function()
	local s = Embers.New({ "A", "B" }, 3)
	Embers.Roll(s, 6); Embers.Bank(s, "A"); Embers.Roll(s, 3)
	eq(Embers.Roll(s, 1), true)
	eq(s.round, 2); eq(s.players.A.total, 6); eq(s.players.B.total, 0)
	eq(s.players.A.stoking, true); eq(s.players.B.stoking, true)
end)

test("round ends when everyone has banked", function()
	local s = Embers.New({ "A", "B" }, 3)
	Embers.Roll(s, 5); Embers.Bank(s, "A"); Embers.Bank(s, "B")
	eq(s.round, 2); eq(s.players.B.total, 5)
end)

test("game ends after the last round with the high total winning", function()
	local s = Embers.New({ "A", "B", "C" }, 1)
	Embers.Roll(s, 6); Embers.Bank(s, "B"); Embers.Roll(s, 2); Embers.Bank(s, "C"); Embers.Roll(s, 1)
	eq(s.over, true)
	local winners, best = Embers.Winners(s)
	eq(#winners, 1); eq(winners[1], "C"); eq(best, 8)
	eq(Embers.Roll(s, 5), nil)
end)

test("ties split the win", function()
	local s = Embers.New({ "A", "B" }, 1)
	Embers.Roll(s, 3); Embers.Bank(s, "A"); Embers.Bank(s, "B")
	eq(#Embers.Winners(s), 2)
end)

test("leavers forfeit and can't win", function()
	local s = Embers.New({ "A", "B" }, 2)
	Embers.Roll(s, 6); Embers.Bank(s, "A"); Embers.Leave(s, "A")
	eq(s.players.B.stoking, true)
	Embers.Leave(s, "B")
	eq(s.round, 2)
	eq(#Embers.Winners(s), 0)
end)

-- Money ----------------------------------------------------------------------
test("parses coin strings", function()
	eq(ns.ParseMoney("5g20s3c"), 52003)
	eq(ns.ParseMoney("35s"), 3500)
	eq(ns.ParseMoney(" 1g 5c "), 10005)
	eq(ns.ParseMoney("250"), 250)
	eq(ns.ParseMoney("5x"), nil)
	eq(ns.ParseMoney("g5"), nil)
	eq(ns.ParseMoney(""), nil)
end)

test("dialled amounts stop where the next coin takes over", function()
	eq(ns.COIN_UNITS[1].max, 100); eq(ns.COIN_UNITS[2].max, 99); eq(ns.COIN_UNITS[3].max, 99)
end)

test("formats coins with textures", function()
	local function plain(copper) return (ns.CoinString(copper):gsub("|T.-|t", "")) end
	eq(plain(52003), "5 20 3"); eq(plain(100), "1"); eq(plain(0), "0"); eq(plain(10001), "1 1")
	eq(ns.CoinString(50):find("UI-CopperIcon", 1, true) ~= nil, true)
end)

-- Ledger ---------------------------------------------------------------------
local Ledger = ns.Ledger
local function Tbl(stake, seats)
	local t = { host = "H", stake = stake, seats = seats, state = "open" }
	Ledger.Init(t)
	return t
end

test("unpaid players sit out; the host never owes", function()
	local t = Tbl(500, { "H", "A", "B" })
	Ledger.Credit(t, "A", 500)
	Ledger.Credit(t, "B", 300)
	eq(Ledger.Owes(t, "H"), 0); eq(Ledger.Owes(t, "B"), 200)
	local players = Ledger.Eligible(t)
	eq(#players, 2); eq(players[1], "H"); eq(players[2], "A")
	local payins = Ledger.PayIns(t)
	eq(#payins, 1); eq(payins[1][1], "B"); eq(payins[1][2], 200)
end)

test("free tables need no trades", function()
	local t = Tbl(0, { "H", "A" })
	eq(#Ledger.Eligible(t), 2); eq(#Ledger.PayIns(t), 0)
end)

test("the pot goes to the winner as credit, host money stays out", function()
	local t = Tbl(500, { "H", "A", "B" })
	Ledger.Credit(t, "A", 500); Ledger.Credit(t, "B", 500)
	Ledger.Commit(t, Ledger.Eligible(t))
	eq(Ledger.Balance(t, "A"), 0)
	eq(Ledger.Settle(t, { "A" }), 1500)
	eq(Ledger.Balance(t, "A"), 1500); eq(Ledger.Balance(t, "B"), 0); eq(Ledger.Balance(t, "H"), 0)
	eq(t.committed, nil)
end)

test("split pots give odd coppers to the first winner", function()
	local t = Tbl(5, { "H", "A", "B" })
	Ledger.Credit(t, "A", 5); Ledger.Credit(t, "B", 5)
	Ledger.Commit(t, Ledger.Eligible(t))
	eq(Ledger.Settle(t, { "A", "B" }), 7)
	eq(Ledger.Balance(t, "A"), 8); eq(Ledger.Balance(t, "B"), 7)
end)

test("an abandoned game refunds stakes", function()
	local t = Tbl(500, { "H", "A" })
	Ledger.Credit(t, "A", 800)
	Ledger.Commit(t, Ledger.Eligible(t))
	Ledger.Void(t)
	eq(Ledger.Balance(t, "A"), 800); eq(t.committed, nil)
end)

test("cash-outs and leavers queue for payout until paid", function()
	local t = Tbl(500, { "H", "A", "B" })
	Ledger.Credit(t, "A", 1200); Ledger.Credit(t, "B", 700)
	t.cashout.A = true
	t.seats = { "H", "A" }; Ledger.Leave(t, "B")
	local out = Ledger.Payouts(t)
	eq(#out, 2); eq(out[1][1], "A"); eq(out[1][2], 1200); eq(out[2][1], "B")
	eq(#Ledger.Eligible(t), 1)
	Ledger.Credit(t, "A", -1200); Ledger.Credit(t, "B", -700)
	eq(#Ledger.Payouts(t), 0); eq(t.cashout.A, nil); eq(t.left.B, nil)
end)

test("settling pays back everyone holding credit", function()
	local t = Tbl(500, { "H", "A", "B" })
	Ledger.Credit(t, "A", 500)
	t.state = "settling"
	local out = Ledger.Payouts(t)
	eq(#out, 1); eq(out[1][1], "A")
end)

test("a table can pass only while the host holds no gold", function()
	local t = Tbl(500, { "H", "A" })
	eq(Ledger.Empty(t), true)
	Ledger.Credit(t, "A", 500)
	eq(Ledger.Empty(t), false)
	Ledger.Credit(t, "A", -500)
	eq(Ledger.Empty(t), true)
	Ledger.Credit(t, "A", 500); Ledger.Commit(t, Ledger.Eligible(t))
	eq(Ledger.Empty(t), false)
end)

test("for-fun tables can always pass, even mid-game", function()
	local t = Tbl(0, { "H", "A" })
	Ledger.Commit(t, Ledger.Eligible(t))
	eq(Ledger.Empty(t), true)
end)

-- Deathroll ------------------------------------------------------------------
local Deathroll = ns.Games.deathroll

local function rolls(s, values)
	for _, pair in ipairs(values) do
		eq(Deathroll.Roll(s, pair[1], pair[2]), true)
	end
end

local function names(list) return table.concat(list, ",") end

test("all out, even count: highest and lowest are knocked out", function()
	local s = Deathroll.New({ "A", "B", "C", "D" })
	eq(s.phase, "round")
	rolls(s, { { "A", 10 }, { "B", 90 }, { "C", 50 }, { "D", 30 } })
	eq(s.out.B, "highest"); eq(s.out.A, "lowest")
	eq(s.phase, "duel"); eq(names(Deathroll.Alive(s)), "C,D")
	eq(s.duel.roller, "C")
end)

test("all out, odd count: only the highest goes", function()
	local s = Deathroll.New({ "A", "B", "C" })
	rolls(s, { { "A", 10 }, { "B", 90 }, { "C", 50 } })
	eq(s.out.B, "highest"); eq(s.out.A, nil)
	eq(s.phase, "duel"); eq(names(Deathroll.Alive(s)), "A,C")
end)

test("five players: one out, then two, then the duel", function()
	local s = Deathroll.New({ "A", "B", "C", "D", "E" })
	rolls(s, { { "A", 5 }, { "B", 60 }, { "C", 20 }, { "D", 80 }, { "E", 40 } })
	eq(names(Deathroll.Alive(s)), "A,B,C,E"); eq(s.phase, "round"); eq(s.round, 2)
	rolls(s, { { "A", 70 }, { "B", 10 }, { "C", 30 }, { "E", 90 } })
	eq(s.out.E, "highest"); eq(s.out.B, "lowest")
	eq(s.phase, "duel"); eq(names(Deathroll.Alive(s)), "A,C")
end)

test("a tie for highest re-rolls among only the tied players", function()
	local s = Deathroll.New({ "A", "B", "C", "D" })
	rolls(s, { { "A", 90 }, { "B", 90 }, { "C", 50 }, { "D", 10 } })
	eq(s.phase, "tie"); eq(names(Deathroll.Waiting(s)), "A,B")
	eq(Deathroll.Roll(s, "C", 5), false)
	rolls(s, { { "A", 20 }, { "B", 70 } })
	eq(s.out.B, "highest"); eq(s.out.D, "lowest")
	eq(s.phase, "duel"); eq(names(Deathroll.Alive(s)), "A,C")
end)

test("a tie for lowest re-rolls among only the tied players", function()
	local s = Deathroll.New({ "A", "B", "C", "D" })
	rolls(s, { { "A", 10 }, { "B", 10 }, { "C", 50 }, { "D", 90 } })
	eq(s.out.D, "highest"); eq(s.phase, "tie"); eq(names(Deathroll.Waiting(s)), "A,B")
	rolls(s, { { "A", 5 }, { "B", 3 } })
	eq(s.out.B, "lowest"); eq(names(Deathroll.Alive(s)), "A,C"); eq(s.phase, "duel")
end)

test("everyone tied: highest re-roll, then a lowest re-roll", function()
	local s = Deathroll.New({ "A", "B", "C", "D" })
	rolls(s, { { "A", 50 }, { "B", 50 }, { "C", 50 }, { "D", 50 } })
	eq(names(Deathroll.Waiting(s)), "A,B,C,D")
	rolls(s, { { "A", 1 }, { "B", 2 }, { "C", 3 }, { "D", 4 } })
	eq(s.out.D, "highest"); eq(s.phase, "tie"); eq(names(Deathroll.Waiting(s)), "A,B,C")
	rolls(s, { { "A", 9 }, { "B", 8 }, { "C", 7 } })
	eq(s.out.C, "lowest"); eq(names(Deathroll.Alive(s)), "A,B"); eq(s.phase, "duel")
end)

test("the duel chains ranges and a 1 loses", function()
	local s = Deathroll.New({ "A", "B" })
	eq(s.phase, "duel")
	local lo, hi = Deathroll.Range(s, "A")
	eq(lo, 1); eq(hi, 100)
	eq(Deathroll.Range(s, "B"), nil)
	eq(Deathroll.Roll(s, "B", 40), false)
	eq(Deathroll.Roll(s, "A", 101), false)
	eq(Deathroll.Roll(s, "A", 40, 99), false)
	eq(Deathroll.Roll(s, "A", 40, 100), true)
	local _, max = Deathroll.Range(s, "B")
	eq(max, 40)
	eq(Deathroll.Roll(s, "B", 41), false)
	eq(Deathroll.Roll(s, "B", 12), true)
	eq(select(2, Deathroll.Range(s, "A")), 12)
	eq(Deathroll.Roll(s, "A", 1), true)
	eq(s.over, true); eq(s.winner, "B"); eq(s.out.A, "rolled 1")
end)

test("nobody rolls twice in a round or out of turn", function()
	local s = Deathroll.New({ "A", "B", "C" })
	eq(Deathroll.Roll(s, "A", 10), true)
	eq(Deathroll.Roll(s, "A", 20), false)
	eq(Deathroll.Roll(s, "Z", 20), false)
	eq(Deathroll.Roll(s, "B", 0), false)
end)

test("folding in the duel hands the win to the other player", function()
	local s = Deathroll.New({ "A", "B" })
	eq(Deathroll.Fold(s, "A"), true)
	eq(s.over, true); eq(s.winner, "B"); eq(s.out.A, "folded")
	eq(Deathroll.Fold(s, "B"), false)
end)

test("folding before rolling drops you and the round carries on", function()
	local s = Deathroll.New({ "A", "B", "C" })
	rolls(s, { { "A", 30 } })
	Deathroll.Fold(s, "B")
	eq(s.phase, "round")
	rolls(s, { { "C", 60 } })
	eq(s.out.B, "folded"); eq(s.phase, "duel"); eq(names(Deathroll.Alive(s)), "A,C")
end)

test("a fold that leaves one player standing ends the game", function()
	local s = Deathroll.New({ "A", "B", "C" })
	Deathroll.Fold(s, "A")
	eq(s.over, false)
	Deathroll.Fold(s, "B")
	eq(s.over, true); eq(s.winner, "C")
end)

test("everyone folding together leaves no winner", function()
	local s = Deathroll.New({ "A", "B", "C" })
	eq(Deathroll.FoldMany(s, { "A", "B", "C" }), true)
	eq(s.over, true); eq(s.winner, nil)
end)

test("both duelists timing out together leaves no winner", function()
	local s = Deathroll.New({ "A", "B" })
	Deathroll.FoldMany(s, { "A", "B" })
	eq(s.over, true); eq(s.winner, nil)
end)

test("a fold during a tie-break settles it", function()
	local s = Deathroll.New({ "A", "B", "C", "D" })
	rolls(s, { { "A", 90 }, { "B", 90 }, { "C", 50 }, { "D", 10 } })
	Deathroll.Fold(s, "A")
	eq(s.phase, "tie")
	rolls(s, { { "B", 33 } })
	eq(s.out.A, "folded"); eq(s.out.B, "highest")
end)

test("the tally tracks wins, losses, net gold and streaks", function()
	local t = Tbl(500, { "H", "A", "B" })
	Ledger.Credit(t, "A", 500); Ledger.Credit(t, "B", 500)
	local dealt = Ledger.Eligible(t)
	Ledger.Commit(t, dealt)
	local share = Ledger.Settle(t, { "A" })
	Ledger.Record(t, dealt, { "A" }, share)
	eq(t.tally.A.w, 1); eq(t.tally.A.net, 1000); eq(t.tally.A.streak, 1)
	eq(t.tally.B.l, 1); eq(t.tally.B.net, -500); eq(t.tally.B.streak, -1)
	eq(t.tally.H.l, 1); eq(t.tally.H.net, -500)
	Ledger.Record(t, dealt, { "B" }, 1500)
	eq(t.tally.A.streak, -1); eq(t.tally.B.streak, 1); eq(t.tally.A.net, 500)
	Ledger.Record(t, dealt, { "B" }, 1500)
	eq(t.tally.B.streak, 2); eq(t.tally.A.streak, -2)
end)

test("for-fun tables tally wins but no gold", function()
	local t = Tbl(0, { "H", "A" })
	Ledger.Record(t, { "H", "A" }, { "A" }, 0)
	eq(t.tally.A.w, 1); eq(t.tally.A.net, 0); eq(t.tally.H.l, 1)
end)

-- Side bets ------------------------------------------------------------------
local Bets = ns.Bets

-- A table with two rounds, holding credit for the given players.
local function Market(cut, credit)
	local t = { host = "H", stake = 0, seats = { "H", "A", "B", "C" }, state = "open" }
	Ledger.Init(t)
	for who, copper in pairs(credit or {}) do Ledger.Credit(t, who, copper) end
	t.market = Bets.NewMarket(cut)
	Bets.AddRound(t.market, "Oppa vs Gopher", { "Oppa", "Gopher" })
	Bets.AddRound(t.market, "Second fight", { "Ratty", "Toad" })
	return t
end

test("rounds carry their game mode and the cut choices are fixed", function()
	local t = Market(0, {})
	Bets.AddRound(t.market, "Rats", { "A", "B", "C" }, 0, "Critter Race")
	eq(t.market.rounds[1].game, "Custom"); eq(t.market.rounds[3].game, "Critter Race")
	eq(table.concat(Bets.CUTS, ","), "2,5,10,20")
end)

test("a bet counts once it's paid from held credit", function()
	local t = Market(0, { A = 500 })
	local ok, bet = Bets.Place(t, "A", 1, 1, 300)
	eq(ok, true); eq(bet.paid, true); eq(Ledger.Balance(t, "A"), 200)
	ok, bet = Bets.Place(t, "B", 1, 2, 300)
	eq(ok, true); eq(bet.paid, false)
	local pools, total = Bets.Pools(t.market, 1)
	eq(pools[1], 300); eq(pools[2], 0); eq(total, 300)
	Ledger.Credit(t, "B", 300)
	Bets.Fund(t)
	eq(bet.paid, true); eq(Ledger.Balance(t, "B"), 0)
	eq(select(2, Bets.Pools(t.market, 1)), 600)
end)

test("owing bettors are listed until they pay", function()
	local t = Market(0, { A = 100 })
	Bets.Place(t, "A", 1, 1, 300)
	Bets.Place(t, "B", 1, 2, 500)
	local owing = Bets.Owing(t)
	eq(#owing, 2); eq(owing[1][1], "A"); eq(owing[1][2], 200); eq(owing[2][2], 500)
	eq(Bets.Unpaid(t.market, "A"), 300)
end)

test("locking keeps unpaid bets on the books until the games begin", function()
	local t = Market(0, { A = 500 })
	Bets.Place(t, "A", 1, 1, 500)
	Bets.Place(t, "B", 1, 2, 500)
	eq(Bets.Lock(t, 1), 1)
	eq(t.market.rounds[1].state, "locked"); eq(#t.market.bets, 2)
	eq(Bets.Place(t, "C", 1, 1, 100), false)
	eq(Bets.Lock(t, 1), false)
	eq(Bets.Unpaid(t.market, "B"), 500)
	Ledger.Credit(t, "B", 500)
	Bets.Fund(t)
	eq(t.market.bets[2].paid, true)
end)

test("the card moves from betting to payment to live to done", function()
	local t = Market(0, { A = 500 })
	eq(Bets.Phase(t.market), "betting")
	Bets.Place(t, "A", 1, 1, 500); Bets.Place(t, "B", 2, 2, 300)
	Bets.Lock(t, 1)
	eq(Bets.Phase(t.market), "betting")
	Bets.Lock(t, 2)
	eq(Bets.Phase(t.market), "payment")
	eq(Bets.Begin(t), 1)
	eq(#t.market.bets, 1)
	eq(Bets.Phase(t.market), "live")
	eq(t.market.rounds[1].started, true)
	Bets.Resolve(t, 1, 1); Bets.Void(t, 2)
	eq(Bets.Phase(t.market), "done")
end)

test("the payment list totals what each bettor owes across rounds", function()
	local t = Market(0, { A = 200, C = 900 })
	Bets.Place(t, "A", 1, 1, 200)
	Bets.Place(t, "A", 2, 1, 300)
	Bets.Place(t, "B", 1, 2, 500)
	Bets.Place(t, "C", 2, 2, 100)
	Bets.Place(t, "H", 1, 1, 50, true)
	local rows, owed, paid = Bets.Payments(t)
	eq(#rows, 3)
	eq(rows[1].who, "B"); eq(rows[1].owes, 500)
	eq(rows[2].who, "A"); eq(rows[2].total, 500); eq(rows[2].paid, 200); eq(rows[2].owes, 300)
	eq(rows[3].who, "C"); eq(rows[3].owes, 0)
	eq(owed, 800); eq(paid, 300)
end)

test("a payment covers every unpaid bet a player has across locked rounds", function()
	local t = Market(0, {})
	Bets.Place(t, "A", 1, 1, 200); Bets.Place(t, "A", 2, 2, 300)
	Bets.Lock(t, 1); Bets.Lock(t, 2)
	eq(Bets.Owing(t)[1][2], 500)
	Ledger.Credit(t, "A", 500)
	Bets.Fund(t)
	eq(#Bets.Owing(t), 0); eq(Bets.Begin(t), 0); eq(#t.market.bets, 2)
end)

test("winners split the pool in proportion to their bets", function()
	local t = Market(0, { A = 500, B = 500, C = 1000 })
	Bets.Place(t, "A", 1, 1, 500); Bets.Place(t, "B", 1, 1, 500); Bets.Place(t, "C", 1, 2, 1000)
	local ok, summary = Bets.Resolve(t, 1, 1)
	eq(ok, true); eq(summary.refunded, false); eq(summary.paidOut, 2000)
	eq(Ledger.Balance(t, "A"), 1000); eq(Ledger.Balance(t, "B"), 1000); eq(Ledger.Balance(t, "C"), 0)
	eq(t.tally.A.w, 1); eq(t.tally.A.net, 500); eq(t.tally.C.l, 1); eq(t.tally.C.net, -1000)
	eq(t.market.rounds[1].state, "done")
end)

test("uneven bets pay by share and the host cut comes off the top", function()
	local t = Market(5, { A = 300, B = 100, C = 600 })
	Bets.Place(t, "A", 1, 1, 300); Bets.Place(t, "B", 1, 1, 100); Bets.Place(t, "C", 1, 2, 600)
	local _, summary = Bets.Resolve(t, 1, 1)
	eq(summary.cut, 50)
	eq(Ledger.Balance(t, "A"), 712); eq(Ledger.Balance(t, "B"), 237)
	local odds = Bets.Odds(t.market, 1)
	eq(math.abs(odds[1] - 950 / 400) < 1e-9, true)
end)

test("a round nobody bet against refunds everyone", function()
	local t = Market(5, { A = 500, B = 500 })
	Bets.Place(t, "A", 1, 1, 500); Bets.Place(t, "B", 1, 1, 500)
	local _, summary = Bets.Resolve(t, 1, 1)
	eq(summary.refunded, true); eq(Ledger.Balance(t, "A"), 500); eq(Ledger.Balance(t, "B"), 500)
	eq(t.tally, nil)
end)

test("a round where nobody backed the winner refunds everyone", function()
	local t = Market(0, { A = 500 })
	Bets.Place(t, "A", 1, 1, 500)
	local _, summary = Bets.Resolve(t, 1, 2)
	eq(summary.refunded, true); eq(Ledger.Balance(t, "A"), 500)
end)

test("voiding a round returns every stake", function()
	local t = Market(0, { A = 500, B = 400 })
	Bets.Place(t, "A", 1, 1, 500); Bets.Place(t, "B", 1, 2, 400)
	eq(Bets.Void(t, 1), true)
	eq(Ledger.Balance(t, "A"), 500); eq(Ledger.Balance(t, "B"), 400)
	eq(#t.market.bets, 0); eq(t.market.rounds[1].state, "void")
	eq(Bets.Void(t, 1), false)
end)

test("rounds are independent, one bet per player per round", function()
	local t = Market(0, { A = 1000, B = 500 })
	eq(Bets.Place(t, "A", 1, 1, 500), true)
	local again, why = Bets.Place(t, "A", 1, 2, 100)
	eq(again, false); eq(why, "you already have a bet on that round")
	eq(Bets.Place(t, "A", 2, 2, 100), true)
	Bets.Place(t, "B", 1, 2, 500)
	eq(select(2, Bets.Pools(t.market, 1)), 1000); eq(select(2, Bets.Pools(t.market, 2)), 100)
	Bets.Resolve(t, 1, 2)
	eq(Ledger.Balance(t, "B"), 1000); eq(t.market.rounds[2].state, "open")
	eq(Ledger.Balance(t, "A"), 400)
end)

test("an unpaid bet can be cancelled and placed again", function()
	local t = Market(0, {})
	Bets.Place(t, "A", 1, 1, 300)
	eq(Bets.Place(t, "A", 1, 2, 300), false)
	eq(Bets.CancelUnpaid(t, "A", 1), 1)
	eq(Bets.Place(t, "A", 1, 2, 300), true)
end)

test("the host bets for free and is never credited", function()
	local t = Market(0, { A = 500 })
	local _, hostBet = Bets.Place(t, "H", 1, 1, 500, true)
	eq(hostBet.paid, true)
	Bets.Place(t, "A", 1, 2, 500)
	Bets.Resolve(t, 1, 1)
	eq(Ledger.Balance(t, "H"), 0); eq(Ledger.Balance(t, "A"), 0)
end)

test("unpaid bets can be cancelled, and the host may only hold gold for paid ones", function()
	local t = Market(0, { A = 500 })
	Bets.Place(t, "B", 1, 1, 200)
	eq(Bets.HoldsGold(t), false)
	eq(Bets.CancelUnpaid(t, "B", 1), 1); eq(#t.market.bets, 0)
	Bets.Place(t, "A", 1, 1, 500)
	eq(Bets.HoldsGold(t), true)
	Bets.Resolve(t, 1, 1)
	eq(Bets.HoldsGold(t), false)
end)

test("pretend-gold bets never make the host hold gold, real paid ones do", function()
	local t = Market(0, { A = 300 })
	Bets.Place(t, "B", 1, 1, 100, true)
	eq(Bets.HoldsGold(t), false)
	Bets.Place(t, "A", 1, 2, 300)
	eq(Bets.HoldsGold(t), true)
end)

test("a round can be removed until real money is paid in on it, and the rest renumber", function()
	local t = Market(0, { A = 500 })
	Bets.AddRound(t.market, "Third", { "X", "Y" })
	Bets.Place(t, "A", 2, 1, 500)
	eq(Bets.CanRemove(t, 2), false)
	eq(Bets.RemoveRound(t, 2), false)
	Bets.Place(t, "B", 1, 1, 100)
	Bets.Place(t, "C", 1, 2, 100, true)
	Bets.Place(t, "C", 3, 1, 100, true)
	eq(Bets.CanRemove(t, 1), true)
	eq(Bets.RemoveRound(t, 1), true)
	eq(#t.market.rounds, 2); eq(t.market.rounds[1].title, "Second fight"); eq(t.market.rounds[2].title, "Third")
	eq(#t.market.bets, 2)
	eq(t.market.bets[1].round, 1); eq(t.market.bets[2].round, 2)
	eq(Ledger.Balance(t, "A"), 0)
end)

test("a called-off round has nothing paid in and can then be removed", function()
	local t = Market(0, { A = 500 })
	Bets.Place(t, "A", 1, 1, 500)
	eq(Bets.CanRemove(t, 1), false)
	Bets.Void(t, 1)
	eq(Bets.CanRemove(t, 1), true)
	eq(Bets.RemoveRound(t, 1), true)
	eq(#t.market.rounds, 1); eq(Ledger.Balance(t, "A"), 500)
end)

test("a preview says what a new bet would win", function()
	local t = Market(0, { A = 500, B = 500 })
	Bets.Place(t, "A", 1, 1, 500)
	eq(Bets.Preview(t.market, 1, 2, 500), 500 + 500)
	eq(Bets.Preview(t.market, 1, 1, 500), 500)
	Bets.Place(t, "B", 1, 2, 500)
	eq(Bets.Preview(t.market, 1, 2, 500), math.floor(1500 * 500 / 1000))
end)

test("bad bets are refused", function()
	local t = Market(0, { A = 500 })
	eq(Bets.Place(t, "A", 9, 1, 100), false)
	eq(Bets.Place(t, "A", 1, 3, 100), false)
	eq(Bets.Place(t, "A", 1, 1, 0), false)
	eq(Bets.Place(t, "A", 1, 1, -5), false)
	eq(Bets.Place(t, "A", 1, 1, ns.BET_CAP + 1), false)
end)

-- The Odd Man Out ------------------------------------------------------------
local Odd = ns.Games.oddmanout

local function picked(s, list)
	for _, p in ipairs(list) do eq(Odd.Pick(s, p[1], p[2]), true) end
end
local function oddRolls(s, list)
	for _, p in ipairs(list) do eq(Odd.Roll(s, p[1], p[2]), true) end
end

test("the die is d10 for five or fewer players and d20 for six or more", function()
	eq(Odd.RangeFor(2), 10); eq(Odd.RangeFor(5), 10); eq(Odd.RangeFor(6), 20); eq(Odd.RangeFor(10), 20)
	eq(Odd.New({ "A", "B", "C", "D", "E" }).range, 10)
	eq(Odd.New({ "A", "B", "C", "D", "E", "F" }).range, 20)
end)

test("picks are checked against the die and can change until the last one is in", function()
	local s = Odd.New({ "A", "B", "C" })
	eq(Odd.Pick(s, "A", 11), false); eq(Odd.Pick(s, "A", 0), false); eq(Odd.Pick(s, "A", 2.5), false)
	eq(Odd.Pick(s, "Z", 3), false)
	eq(Odd.Pick(s, "A", 5), true); eq(Odd.Pick(s, "A", 6), true)
	eq(s.picks.A, 6); eq(s.phase, "pick")
	picked(s, { { "B", 7 }, { "C", 9 } })
	eq(s.phase, "roll")
	eq(Odd.Pick(s, "A", 1), false)
end)

test("you're knocked out when someone else rolls your number", function()
	local s = Odd.New({ "A", "B", "C" })
	picked(s, { { "A", 5 }, { "B", 7 }, { "C", 9 } })
	oddRolls(s, { { "A", 7 }, { "B", 1 }, { "C", 2 } })
	eq(s.out.B.reason, "knocked out"); eq(s.out.B.pick, 7)
	eq(names(Odd.Alive(s)), "A,C"); eq(s.phase, "roll"); eq(s.round, 2)
	eq(s.picks.A, 5)
	eq(names(s.last.knocked), "B")
end)

test("your own roll never knocks you out", function()
	local s = Odd.New({ "A", "B", "C" })
	picked(s, { { "A", 5 }, { "B", 7 }, { "C", 9 } })
	oddRolls(s, { { "A", 5 }, { "B", 1 }, { "C", 2 } })
	eq(names(Odd.Alive(s)), "A,B,C"); eq(#s.last.knocked, 0); eq(s.round, 2)
end)

test("players can share a number: only the others are hit by a roll of it", function()
	local s = Odd.New({ "A", "B", "C" })
	picked(s, { { "A", 5 }, { "B", 5 }, { "C", 3 } })
	oddRolls(s, { { "A", 5 }, { "B", 1 }, { "C", 2 } })
	eq(names(Odd.Alive(s)), "A,C")
	local t = Odd.New({ "A", "B", "C" })
	picked(t, { { "A", 5 }, { "B", 5 }, { "C", 3 } })
	oddRolls(t, { { "A", 5 }, { "B", 5 }, { "C", 2 } })
	eq(t.over, true); eq(t.winner, "C")
end)

test("a round that would knock everyone out is replayed", function()
	local s = Odd.New({ "A", "B" })
	picked(s, { { "A", 1 }, { "B", 2 } })
	oddRolls(s, { { "A", 2 }, { "B", 1 } })
	eq(s.last.wipeout, true); eq(#s.last.knocked, 0)
	eq(names(Odd.Alive(s)), "A,B"); eq(s.wipeouts, 1); eq(s.phase, "roll"); eq(s.round, 2)
end)

test("the last player standing wins", function()
	local s = Odd.New({ "A", "B", "C" })
	picked(s, { { "A", 5 }, { "B", 7 }, { "C", 9 } })
	oddRolls(s, { { "A", 7 }, { "B", 1 }, { "C", 2 } })
	oddRolls(s, { { "A", 9 }, { "C", 1 } })
	eq(s.over, true); eq(s.winner, "A"); eq(s.phase, "over")
	eq(names(Odd.Winners(s)), "A")
end)

test("the die shrinks as players drop and everyone picks again", function()
	local list = {}
	for i = 1, 7 do list[i] = "P" .. i end
	local s = Odd.New(list)
	eq(s.range, 20)
	for i = 1, 7 do eq(Odd.Pick(s, "P" .. i, i), true) end
	for i = 1, 7 do
		local v = (i == 1 and 2) or (i == 3 and 4) or 20
		eq(Odd.Roll(s, "P" .. i, v), true)
	end
	eq(names(Odd.Alive(s)), "P1,P3,P5,P6,P7")
	eq(s.range, 10); eq(s.phase, "pick"); eq(next(s.picks), nil)
	eq(Odd.Pick(s, "P1", 15), false)
	for _, name in ipairs(Odd.Alive(s)) do eq(Odd.Pick(s, name, 3), true) end
	eq(s.phase, "roll")
end)

test("rolls must be on the die and only once a round", function()
	local s = Odd.New({ "A", "B", "C" })
	picked(s, { { "A", 5 }, { "B", 7 }, { "C", 9 } })
	eq(Odd.Roll(s, "A", 11), false); eq(Odd.Roll(s, "A", 0), false)
	eq(Odd.Roll(s, "A", 3, 20), false)
	eq(Odd.Roll(s, "A", 3, 10), true)
	eq(Odd.Roll(s, "A", 4), false)
	eq(Odd.Roll(s, "Z", 4), false)
end)

test("folding in the pick phase, in the roll phase, and with one left", function()
	local s = Odd.New({ "A", "B", "C" })
	picked(s, { { "A", 5 } })
	eq(Odd.Fold(s, "B"), true)
	eq(s.phase, "pick"); eq(names(Odd.Waiting(s)), "C")
	picked(s, { { "C", 9 } })
	eq(s.phase, "roll")

	local t = Odd.New({ "A", "B", "C", "D" })
	picked(t, { { "A", 1 }, { "B", 2 }, { "C", 3 }, { "D", 4 } })
	oddRolls(t, { { "A", 9 }, { "B", 9 } })
	Odd.Fold(t, "C")
	eq(names(Odd.Waiting(t)), "D")
	oddRolls(t, { { "D", 1 } })
	eq(t.out.C.reason, "folded"); eq(t.out.A.reason, "knocked out")
	eq(names(Odd.Alive(t)), "B,D")

	local u = Odd.New({ "A", "B" })
	Odd.Fold(u, "A")
	eq(u.over, true); eq(u.winner, "B")
end)

test("everyone timing out together leaves no winner", function()
	local s = Odd.New({ "A", "B", "C" })
	eq(Odd.FoldMany(s, { "A", "B", "C" }), true)
	eq(s.over, true); eq(s.winner, nil); eq(#Odd.Winners(s), 0)
end)

test("a fold in the pick phase can shrink the die and restart the picks", function()
	local list = {}
	for i = 1, 6 do list[i] = "P" .. i end
	local s = Odd.New(list)
	picked(s, { { "P1", 15 }, { "P2", 12 } })
	Odd.Fold(s, "P3")
	eq(s.range, 10); eq(next(s.picks), nil); eq(#Odd.Waiting(s), 5)
end)

print(("%d passed, %d failed"):format(passed, failed))
os.exit(failed == 0 and 0 or 1)
